# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish Avalonia NuGets

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: read
      packages: write # required to push packages

    steps:
      # Checkout the branch
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: release/11.3.4_Rendering

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check Installed Tools
        run: |
          echo "=== Local Tools ==="
          dotnet tool list
          echo "=== Global Tools ==="
          dotnet tool list --global


      # Restore NUKE tools
      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Clean and Restore NUKE Tools
        run: |
          rm -rf ~/.nuget/packages/numerge
          dotnet tool restore

      # Run NUKE build to create NuGet packages
      - name: Run NUKE Build
        run: ./build.sh CreateNugetPackages --configuration Release --force-nuget-version 11.3.4.${{ github.run_number }}
        shell: bash
        
  publish:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ./artifacts

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" --source "https://nuget.pkg.github.com/Trendiot/index.json" --api-key ${GITHUB_TOKEN} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
